# -*- coding: utf-8 -*-
"""Multi‑Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTNP6Gl8FmuI3pt1tKb-QXPNJMhOFbyd

# Taxonomy, RACI, Incentives, and Production Patterns in a Multi-Agent Research System

This notebook is a lecture-style walkthrough you can run top-to-bottom in Google Colab or locally. It builds one multi-agent research system end-to-end and uses it to teach seven ideas, in order:

1. **Taxonomy** — what roles exist in the system and why they are separated.
2. **RACI** — who is responsible, who is accountable, who is consulted, and who is informed.
3. **Orchestration** — how the work actually flows, expressed as a LangGraph `StateGraph`.
4. **Incentives** — how a system can look structurally correct on paper but still drift into bad behavior if its rewards are misaligned.
5. **Serialization** — what crosses the boundary when agents stop sharing memory, and why your schemas were already designed for this whether you noticed or not.
6. **Communication Protocols (A2A)** — what the message envelope must carry once agents live on different machines, and why each field replaces something that was free in shared memory.
7. **Reflexion** — how appending lessons to episodic memory turns an amnesiac Critic loop into a system that can learn across iterations, and the new failure mode this introduces.
8. **Human-in-the-Loop** — when the automated Critic is not enough, and how RACI itself shifts under risk so that a human becomes Accountable while the Critic moves to Consulted.

This is a teaching notebook, not a production hardening exercise. The code is intentionally direct so the concepts stay visible — every section is one short markdown explanation, one code cell for the concept, and one demo cell that shows the output.

## How the pieces fit together

The first four sections build the system. The last four extend it toward what production actually demands:

- Taxonomy gives you the catalog of roles.
- RACI assigns ownership over those roles.
- Orchestration (LangGraph `StateGraph`) turns that structure into executable behavior.
- Incentives ask what the system will drift toward over many runs, even when the structure is correct.
- Serialization is what happens the moment any of this leaves one Python process.
- Communication protocols are what's needed once agents stop sharing memory entirely.
- Reflexion is a structural change to how the Critic loop remembers failure.
- Human-in-the-Loop is the recognition that for sensitive questions, the right Accountable party is not an agent.

A single anchor question is defined near the top and reused throughout, so every intermediate output stays anchored to the same example.

## How to use this notebook

Run from top to bottom. The pattern is repetitive on purpose: one short markdown explanation, one code cell for one concept, one demo cell. That structure makes the system easier to teach in class — students do not have to jump between many files or wonder where a particular output came from.

A compact way to remember the whole notebook:

| Section | Question it answers |
|---|---|
| Taxonomy | What roles exist? |
| RACI | Who owns what? |
| Orchestration | How does the work flow? |
| Incentives | What will the system drift toward? |
| Serialization | What crosses the boundary? |
| Protocols (A2A) | How do agents speak across it? |
| Reflexion | What does the system remember? |
| Human-in-the-Loop | When does a human decide? |

Eight questions. One small notebook. Same anchor question runs the whole way through.

---

That's the intro, sir. It removes every reference to the vanilla for-loop version, accurately previews all eight sections, and sets up the "structure → extensions" arc that the rest of the notebook actually delivers. Drop it in place of the existing opening and the rest of the book reads as one continuous teaching arc.
"""
from __future__ import annotations

import subprocess
import sys

subprocess.check_call(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "--break-system-packages",
        "langgraph>=0.2.50",
        "langchain-core>=0.3.0",
        "langchain-openai>=0.2.0",
        "rich",
        "python-dotenv",
        "ddgs",
    ]
)

print("Dependencies installed.")

import os
import time
import warnings
from dataclasses import dataclass, field
from typing import TypedDict, Optional

warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)

from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

load_dotenv()
console = Console()

try:
    from google.colab import userdata

    if not os.environ.get("OPENAI_API_KEY"):
        os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
except Exception:
    pass

if os.environ.get("OPENAI_API_KEY"):
    print("OPENAI_API_KEY is available.")
else:
    print(
        "OPENAI_API_KEY not found. In Colab, add it in Secrets with the name OPENAI_API_KEY before running LLM cells."
    )

"""## Anchor Question

We place the question near the top so every later concept can point back to the same concrete example.

This question is deliberately chosen to trigger multiple roles:

- it is **comparative**, so deeper reading is useful,
- it is **financial/tax-related**, so the Compliance role should be activated,
- it gives us a clean example for taxonomy, RACI, and incentives all in one run.
"""

QUESTION = "Deep Research on Jobs in demand"
MAX_ITERATIONS = 3

print("Question:")
print(QUESTION)

"""## Taxonomy: What Roles Exist?

A **taxonomy** is a classification of roles. In this notebook, taxonomy does not mean hierarchy, seniority, or an org chart. It means: **what kinds of workers exist in this system, and what distinct mission does each one have?**

This separation matters because a multi-agent system is easier to reason about when each role has a focused job. If one agent tries to plan, search, read, write, review, and manage compliance all at once, the teaching value drops and the control structure becomes blurry.

So the taxonomy gives us a menu of possible capabilities:

- Planner breaks a question into sub-queries.
- Searcher gathers evidence.
- Reader extracts facts from that evidence.
- Writer turns findings into an answer.
- Critic evaluates whether the answer is good enough.
- Compliance adds extra safeguards in sensitive domains.

The taxonomy answers the question: **"What roles are available in this system?"**

### From `RunTrace` (dataclass) to `State` (TypedDict)

In the vanilla version we tracked everything in a `RunTrace` dataclass and threaded it manually through a `for` loop. In LangGraph, the framework already gives us a first-class concept for this: **state**.

The `State` is a `TypedDict` that flows through every node in the graph. Each node receives the current state, does its work, and returns the fields it wants to update. LangGraph merges those updates back into the state automatically.

So conceptually:

- `RunTrace` (vanilla) → `State` (LangGraph) — same fields, different container.
- The orchestrator's `for` loop → a `StateGraph` with conditional edges.
- The manual feedback threading → state mutation on each node.

`RACIEntry` and `IncentiveRisk` stay as dataclasses because they are *outputs* (lookup tables and scan reports), not flowing state. Only the running pipeline data lives in `State`.
"""

Source = dict[str, str]


@dataclass
class RACIEntry:
    task: str
    responsible: str
    accountable: str
    consulted: str = ""
    informed: str = "Team"


@dataclass
class IncentiveRisk:
    name: str
    why: str
    mitigation: str


class State(TypedDict, total=False):
    # The question being researched (input).
    question: str
    # The team of agents selected for this run.
    team: list[str]
    # Working data produced as the graph executes.
    queries: list[str]
    sources: list[Source]
    facts: list[str]
    disclaimer: str
    answer: str
    critic_feedback: str
    # Critic verdict for the conditional edge.
    approved: bool
    issues: list[str]
    # Counters and metadata mirroring the original RunTrace.
    iterations: int
    max_iterations: int
    sources_count: int
    llm_calls: int
    duration_seconds: float
    was_sensitive: bool
    critic_first_pass: bool
    final_answer: str
    # Used only by the Reflexion graph (later in the notebook). Kept as a
    # plain list so the same State works for the basic and Reflexion runs.
    episodic_memory: list

TAXONOMY = {
    "Planner": {
        "mission": "Break the question into smaller search queries.",
        "always": True,
    },
    "Searcher": {
        "mission": "Find sources on the web using DuckDuckGo.",
        "always": True,
    },
    "Reader": {
        "mission": "Read source snippets and extract structured facts.",
        "always": False,
    },
    "Writer": {
        "mission": "Synthesize findings into a clear answer.",
        "always": True,
    },
    "Critic": {
        "mission": "Review the answer and approve or reject it.",
        "always": True,
    },
    "Compliance": {
        "mission": "Add guardrails for sensitive domains.",
        "always": False,
    },
}


def print_taxonomy() -> None:
    table = Table(title="ROLE TAXONOMY", show_lines=True)
    table.add_column("Agent", style="bold cyan")
    table.add_column("Mission")
    table.add_column("Selection")

    for role, info in TAXONOMY.items():
        selection = "Always" if info["always"] else "Conditional"
        table.add_row(role, info["mission"], selection)

    console.print(table)

print_taxonomy()

"""## Team Selection: Which Roles Do We Need For This Question? (Planner, Router)

Taxonomy tells us what roles exist. It does **not** tell us that every role should be used every time.

That is the job of **team selection**.

Team selection is where the system looks at the question and decides which capabilities are worth paying for in this run. This matters because more roles can improve quality, but they also increase time, cost, and coordination overhead.

In this project:

- some roles are always included because they define the backbone of the workflow,
- the Reader is added when the question looks deep or comparative,
- the Compliance role is added when the topic looks sensitive.

This section is useful for teaching the difference between two ideas:

- **taxonomy** = the full catalog of possible roles,
- **team selection** = the active subset chosen for one task.
"""

DEEP_KEYWORDS = [
    "compare",
    "vs",
    "versus",
    "difference",
    "analyze",
    "explain how",
    "tradeoff",
    "trade-off",
    "evaluate",
]

SENSITIVE_KEYWORDS = [
    "medical",
    "diagnosis",
    "treatment",
    "drug",
    "disease",
    "legal",
    "law",
    "lawsuit",
    "tax",
    "investment",
    "financial advice",
    "loan",
    "mortgage",
]


def needs_deep_reading(question: str) -> bool:
    lowered_question = question.lower()
    if len(question.split()) > 15:
        return True
    return any(keyword in lowered_question for keyword in DEEP_KEYWORDS)


def is_sensitive(question: str) -> bool:
    lowered_question = question.lower()
    return any(keyword in lowered_question for keyword in SENSITIVE_KEYWORDS)


def select_team(question: str) -> list[str]:
    team = [role for role, info in TAXONOMY.items() if info["always"]]

    if needs_deep_reading(question):
        team.append("Reader")
        console.print("Deep/comparative question detected -> adding Reader")

    if is_sensitive(question):
        team.append("Compliance")
        console.print("Sensitive domain detected -> adding Compliance")

    return team

# def select_team(question: str, registry: dict, llm) -> list[str]:
#     # Always-on roles: skip the LLM, they're non-negotiable
#     mandatory = [r for r, info in registry.items() if info.get("always")]
#     optional  = {r: info for r, info in registry.items() if not info.get("always")}

#     if not optional:
#         return mandatory

#     catalog = "\n".join(
#         f"- {role}: {info['when_to_use']}" for role, info in optional.items()
#     )

#     prompt = f"""You are routing a question to specialist agents.

# Question: {question}

# Optional specialists available:
# {catalog}

# Return ONLY a JSON array of role names from the list above that should be activated for this question. Return [] if none apply. No prose, no explanation.

# Example: ["Reader", "Compliance"]"""

#     response = llm(prompt)  # whatever your LLM call looks like
#     chosen = json.loads(response.strip())

#     # Defensive: drop anything hallucinated
#     valid = [r for r in chosen if r in optional]

#     return mandatory + valid

team = select_team(QUESTION)
console.print(f"\nSELECTED TEAM ({len(team)} agents): {', '.join(team)}")

"""## RACI: Who Owns What?

Once we know the team, the next question is: **who is doing what, and who is accountable for the result?**

This is exactly the question RACI was invented to answer. RACI stands for:

- **R**esponsible — who actually does the work,
- **A**ccountable — who is on the hook for whether it was done well,
- **C**onsulted — whose input was used,
- **I**nformed — who needs to know what happened.

In this notebook, the Critic is the role that owns quality. So the Critic is **Accountable** for most tasks, even though the Critic does not produce the work itself.

That distinction (R vs A) is the most useful piece of RACI for multi-agent systems. The agent that *produces* an artifact is rarely the same as the agent that *owns* its quality.
"""

def build_raci(team: list[str]) -> list[RACIEntry]:
    entries: list[RACIEntry] = []

    if "Planner" in team:
        entries.append(
            RACIEntry(task="Plan sub-queries", responsible="Planner", accountable="Critic")
        )
    if "Searcher" in team:
        entries.append(
            RACIEntry(
                task="Find sources",
                responsible="Searcher",
                accountable="Critic",
                consulted="Planner",
            )
        )
    if "Reader" in team:
        entries.append(
            RACIEntry(
                task="Extract facts",
                responsible="Reader",
                accountable="Critic",
                consulted="Searcher",
            )
        )
    if "Compliance" in team:
        entries.append(
            RACIEntry(
                task="Add disclaimer",
                responsible="Compliance",
                accountable="Critic",
            )
        )
    if "Writer" in team:
        entries.append(
            RACIEntry(
                task="Write answer",
                responsible="Writer",
                accountable="Critic",
                consulted="Searcher",
            )
        )
    if "Critic" in team:
        entries.append(
            RACIEntry(task="Verify answer", responsible="-", accountable="Critic")
        )

    return entries


def print_raci(raci_entries: list[RACIEntry]) -> None:
    table = Table(title="RACI MATRIX", show_lines=True)
    table.add_column("Task", style="bold")
    table.add_column("R (Responsible)")
    table.add_column("A (Accountable)", style="bold yellow")
    table.add_column("C (Consulted)")
    table.add_column("I (Informed)")

    for entry in raci_entries:
        table.add_row(
            entry.task,
            entry.responsible,
            entry.accountable,
            entry.consulted,
            entry.informed,
        )

    console.print(table)

raci_entries = build_raci(team)
print_raci(raci_entries)

"""## Shared LLM Wrapper

Several agents call the language model. Instead of repeating that code in every agent, we use one shared wrapper.

This is not about production complexity. It simply keeps the notebook easier to read:

- one place to set the model,
- one place to define temperature and token limits,
- one function that the agents can reuse.

Notice the conceptual split:

- the taxonomy defines **who** exists,
- the wrapper defines **how** those roles talk to the LLM.

### What changed from the vanilla version

The vanilla notebook called the OpenAI client directly. We now use `ChatOpenAI` from `langchain_openai`. The interface is essentially the same — `prompt -> string` — but it lets every agent in the graph share one consistent LLM client and makes it trivial to swap providers later.
"""

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

_llm: ChatOpenAI | None = None


def get_llm(max_tokens: int = 500) -> ChatOpenAI:
    """Lazily build a ChatOpenAI client. We keep one instance per token budget
    so the model stays consistent across the notebook."""
    global _llm
    if _llm is None:
        _llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.3)
    return _llm


def call_llm(prompt: str, max_tokens: int = 500) -> str:
    """Send a single user prompt and return the text reply. Same shape as the
    vanilla wrapper - one prompt in, one string out."""
    llm = get_llm(max_tokens=max_tokens).bind(max_tokens=max_tokens)
    response = llm.invoke([HumanMessage(content=prompt)])
    return response.content.strip()

"""## Planner Agent: Break One Big Question Into Smaller Search Tasks

The Planner is the decomposition role.

Its job is not to answer the question directly. Its job is to make the next step easier by turning one broad question into several narrower search queries.

This is a useful design pattern in multi-agent systems because retrieval quality often depends on query quality. If the search queries are vague, the entire downstream pipeline becomes weaker.

So the Planner adds value by making the search space more explicit.
"""

def planner_agent(question: str) -> list[str]:
    prompt = f"""Break this research question into 3 to 5 specific web search queries.
Return ONLY the queries, one per line, no numbering or extra text.

Question: {question}"""
    text = call_llm(prompt, max_tokens=200)
    queries = [line.strip() for line in text.splitlines() if line.strip()]
    return queries[:5]

queries = planner_agent(QUESTION)
print("Planner queries:")
for index, query in enumerate(queries, start=1):
    print(f"{index}. {query}")

"""## Searcher Agent: Gather External Evidence

The Searcher is the retrieval role. It uses DuckDuckGo to gather sources from the open web.

This is the first place where the system leaves its own internal reasoning and touches outside evidence. That makes the Searcher important for both quality and risk:

- strong retrieval can improve factual grounding,
- weak retrieval can poison everything downstream,
- too few sources can make the final answer look polished but thinly supported.

In this notebook, the Searcher returns a simple structure for each source: title, URL, and snippet.
"""

def searcher_agent(queries: list[str]) -> list[Source]:
    try:
        from ddgs import DDGS
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "Searcher agent requires ddgs. Run the setup cell first."
        ) from error

    sources: list[Source] = []
    seen_urls: set[str] = set()

    with DDGS() as ddgs:
        for query in queries:
            try:
                results = list(ddgs.text(query, max_results=3))
                for result in results:
                    url = result.get("href", "")
                    if url and url not in seen_urls:
                        seen_urls.add(url)
                        sources.append(
                            {
                                "title": result.get("title", ""),
                                "url": url,
                                "snippet": result.get("body", ""),
                            }
                        )
            except Exception as error:
                console.print(f"   Search failed for '{query}': {error}")
                continue

    return sources

sources = searcher_agent(queries)
print(f"Collected {len(sources)} unique sources.")

for source in sources[:5]:
    print("-" * 80)
    print(source["title"])
    print(source["url"])
    print(source["snippet"])

"""## Reader Agent: Turn Raw Retrieval Into Explicit Facts

The Searcher gathers evidence, but it does not organize that evidence into usable findings. That is the Reader's job.

The Reader is useful when the question is deep, comparative, or detail-heavy. It reads across source snippets and extracts a smaller set of facts that the Writer can later use.

Conceptually, the Reader helps the system move from **data collection** to **evidence interpretation**.
"""

def reader_agent(question: str, sources: list[Source]) -> list[str]:
    snippets = "\n\n".join(
        f"[{index + 1}] {source['title']}\n{source['snippet']}"
        for index, source in enumerate(sources[:8])
    )
    prompt = f"""Read these source snippets and extract 5-10 key facts relevant to the question.
Return ONLY the facts, one per line, no numbering.

Question: {question}

Sources:
{snippets}"""
    text = call_llm(prompt, max_tokens=600)
    return [line.strip() for line in text.splitlines() if line.strip()]

facts = reader_agent(QUESTION, sources)
print("Reader facts:")
for index, fact in enumerate(facts, start=1):
    print(f"{index}. {fact}")

"""## Compliance Agent: Add Guardrails For Sensitive Topics

Not every question needs Compliance. But when a topic touches medical, legal, financial, or similar high-stakes domains, a system often needs extra safeguards.

In this project, the Compliance role is intentionally simple: it produces a disclaimer that the Writer should include.

The important teaching idea is not the complexity of the implementation. The important idea is that **sensitive domains may require a distinct role with a distinct mission**. That is a taxonomy decision, a team selection decision, and later an incentive design decision.
"""

def compliance_agent(question: str) -> str:
    prompt = f"""This question is in a sensitive domain (medical/legal/financial).
Write ONE sentence disclaimer the answer should include.

Question: {question}"""
    return call_llm(prompt, max_tokens=100)

disclaimer = compliance_agent(QUESTION) if "Compliance" in team else ""
print("Compliance disclaimer:")
print(disclaimer if disclaimer else "Compliance not selected for this question.")

"""## Writer Agent: Turn Findings Into A Usable Answer

The Writer is the synthesis role. It is where the system turns retrieval, reading, and compliance guidance into something a user can consume.

The Writer is not supposed to invent the whole answer from scratch. Ideally, it should draw on the facts, the sources, and any required disclaimer.

This is another useful point for class discussion:

- a system can have good retrieval but poor synthesis,
- or strong synthesis but weak evidence,
- and both cases can produce misleadingly polished answers.

That is one reason the Critic role exists after the Writer.
"""

def writer_agent(
    question: str,
    sources: list[Source],
    facts: list[str],
    disclaimer: str,
    critic_feedback: str = "",
) -> str:
    sources_text = "\n".join(
        f"- {source['title']} ({source['url']})" for source in sources[:8]
    )
    facts_text = "\n".join(f"- {fact}" for fact in facts) if facts else "(none)"
    feedback_text = ""
    if critic_feedback:
        feedback_text = (
            "\n\nPREVIOUS CRITIC FEEDBACK TO ADDRESS:\n"
            f"{critic_feedback}"
        )

    disclaimer_line = (
        f"Include this disclaimer at the end: {disclaimer}" if disclaimer else ""
    )
    prompt = f"""Write a clear, well-structured answer (150-300 words) to the question.
Use the facts and cite sources where appropriate.
{disclaimer_line}

Question: {question}

Facts:
{facts_text}

Sources:
{sources_text}{feedback_text}"""
    return call_llm(prompt, max_tokens=600)

draft_answer = writer_agent(QUESTION, sources, facts, disclaimer)
console.print(Panel(draft_answer, title="WRITER DRAFT", style="bold white"))

"""## Critic Agent: Approve Or Reject The Draft

The Critic is the role that checks the Writer.

It is allowed to reject. That is the entire point. If the Critic only ever approved, the system would have no real quality gate.

In this notebook, the Critic does three things:

- counts sources to make sure the answer was not built on too thin an evidence base,
- counts words to make sure the answer is not suspiciously short,
- asks the LLM whether the answer actually addresses the question.

This is intentionally lightweight. In a real system, the Critic could check for citations, contradictions, hallucinations, or domain-specific rules.
"""

def critic_agent(
    question: str,
    answer: str,
    sources: list[Source],
) -> tuple[bool, list[str]]:
    issues: list[str] = []

    if len(sources) < 3:
        issues.append(f"Too few sources ({len(sources)} found, need at least 3)")

    word_count = len(answer.split())
    if word_count < 100:
        issues.append(f"Answer too brief ({word_count} words, need at least 100)")

    prompt = f"""Does this answer fully address the question?
Reply with EXACTLY one of:
  APPROVE
  REJECT: <one short reason>

Question: {question}

Answer: {answer}"""
    verdict = call_llm(prompt, max_tokens=80)
    if verdict.upper().startswith("REJECT"):
        reason = verdict.split(":", 1)[1].strip() if ":" in verdict else "Incomplete"
        issues.append(f"Aspect check failed: {reason}")

    return len(issues) == 0, issues

approved, issues = critic_agent(QUESTION, draft_answer, sources)
print("Approved:", approved)
print("Issues:")
for issue in issues:
    print("-", issue)
if not issues:
    print("- No issues raised.")

"""## Orchestration with LangGraph: Turn Structure Into Behavior

So far, we have defined roles, chosen a team, built a RACI matrix, and looked at the individual agents.

Now we connect them into a process.

This is the core systems-thinking section of the notebook:

- taxonomy tells us what roles exist,
- team selection tells us which of those roles are active,
- RACI clarifies who does what and who owns quality,
- orchestration makes those design choices actually execute.

### From `for` loop to `StateGraph`

In the vanilla version, the orchestrator was a Python `for` loop that called each agent in order, kept everything in a `RunTrace` dataclass, and looped back to the Writer if the Critic rejected.

In LangGraph, that same logic becomes a **graph**:

- each agent is a **node** that reads `State` and returns updates,
- the order of work is expressed as **edges** between nodes,
- the Critic loop becomes a **conditional edge**: from Critic, go back to Writer if rejected and we still have iterations left, otherwise go to END.

The behaviour is identical. The shape is now declarative — you can see the workflow as a graph rather than as a sequence of `if "Foo" in team:` checks.

Each node also keeps the same `console.print` calls as the vanilla orchestrator, so when the graph runs you still see "Planner -> generating sub-queries...", "Searcher -> searching DuckDuckGo...", and so on, just like before.
"""

from langgraph.graph import StateGraph, START, END


# -----------------------------
# Nodes - one per agent role
# -----------------------------

def planner_node(state: State) -> dict:
    if "Planner" not in state["team"]:
        return {}
    console.print("Planner -> generating sub-queries...")
    queries = planner_agent(state["question"])
    console.print(f"   {len(queries)} queries: {queries}")
    return {
        "queries": queries,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def searcher_node(state: State) -> dict:
    if "Searcher" not in state["team"]:
        return {}
    console.print("Searcher -> searching DuckDuckGo...")
    new_sources = searcher_agent(state.get("queries", []))

    # Merge with any sources already collected, dedup by URL.
    existing = state.get("sources", [])
    combined = existing + new_sources
    seen_urls: set[str] = set()
    deduped: list[Source] = []
    for source in combined:
        url = source.get("url", "")
        if url and url not in seen_urls:
            seen_urls.add(url)
            deduped.append(source)

    console.print(f"   {len(deduped)} unique sources collected so far")
    return {
        "sources": deduped,
        "sources_count": len(deduped),
    }


def reader_node(state: State) -> dict:
    if "Reader" not in state["team"]:
        return {}
    console.print("Reader -> extracting facts...")
    facts = reader_agent(state["question"], state.get("sources", []))
    console.print(f"   {len(facts)} facts extracted")
    return {
        "facts": facts,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def compliance_node(state: State) -> dict:
    if "Compliance" not in state["team"]:
        return {}
    # Only run once - reuse the disclaimer across iterations.
    if state.get("disclaimer"):
        return {}
    console.print("Compliance -> generating disclaimer...")
    disclaimer = compliance_agent(state["question"])
    console.print("   Disclaimer ready")
    return {
        "disclaimer": disclaimer,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def writer_node(state: State) -> dict:
    console.print("Writer -> synthesizing answer...")
    answer = writer_agent(
        state["question"],
        state.get("sources", []),
        state.get("facts", []),
        state.get("disclaimer", ""),
        state.get("critic_feedback", ""),
    )
    console.print(f"   Draft ready ({len(answer.split())} words)")
    # Bump iteration counter every time the Writer runs (one Writer call = one iteration).
    iteration = state.get("iterations", 0) + 1
    console.print(Panel(f"ITERATION {iteration}", style="bold green"))
    return {
        "answer": answer,
        "iterations": iteration,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def critic_node(state: State) -> dict:
    console.print("Critic -> reviewing...")
    approved, issues = critic_agent(
        state["question"],
        state.get("answer", ""),
        state.get("sources", []),
    )

    updates: dict = {
        "approved": approved,
        "issues": issues,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }

    if approved:
        console.print("   APPROVED")
        if state.get("iterations", 0) == 1:
            updates["critic_first_pass"] = True
    else:
        console.print("   REJECTED:")
        for issue in issues:
            console.print(f"      - {issue}")
        updates["critic_feedback"] = "; ".join(issues)
        if state.get("iterations", 0) >= state.get("max_iterations", MAX_ITERATIONS):
            console.print("   Max iterations reached. Returning best draft anyway.")

    return updates


# -----------------------------
# Conditional edge - the Critic loop
# -----------------------------

def critic_router(state: State) -> str:
    """After the Critic, either loop back to the Writer or finish.

    This is the LangGraph equivalent of the vanilla orchestrator's
    `if approved: break / else: continue` block."""
    if state.get("approved", True):
        return "end"
    if state.get("iterations", 0) >= state.get("max_iterations", MAX_ITERATIONS):
        return "end"
    return "writer"


# -----------------------------
# Graph builder
# -----------------------------

def build_research_graph():
    """Wire all the nodes together. The structure is:

        START -> planner -> searcher -> reader -> compliance -> writer -> critic
                                                                           |
                                                       (rejected & retries left)
                                                                           |
                                                                           v
                                                                         writer
                                                                           |
                                                                  (approved or max)
                                                                           |
                                                                           v
                                                                          END
    """
    graph = StateGraph(State)

    graph.add_node("planner", planner_node)
    graph.add_node("searcher", searcher_node)
    graph.add_node("reader", reader_node)
    graph.add_node("compliance", compliance_node)
    graph.add_node("writer", writer_node)
    graph.add_node("critic", critic_node)

    graph.add_edge(START, "planner")
    graph.add_edge("planner", "searcher")
    graph.add_edge("searcher", "reader")
    graph.add_edge("reader", "compliance")
    graph.add_edge("compliance", "writer")
    graph.add_edge("writer", "critic")
    graph.add_conditional_edges(
        "critic",
        critic_router,
        {"writer": "writer", "end": END},
    )

    return graph.compile()


def run_research(question: str, max_iterations: int = 3) -> State:
    """Run the full graph end-to-end. Returns the final State.

    This replaces the vanilla `run_research` for-loop. The print statements
    inside the nodes give us the same step-by-step console trace."""
    print_taxonomy()

    console.print("\nANALYZING QUESTION...")
    team = select_team(question)
    console.print(f"\nSELECTED TEAM ({len(team)} agents): {', '.join(team)}\n")

    raci_entries = build_raci(team)
    print_raci(raci_entries)

    initial_state: State = {
        "question": question,
        "team": team,
        "queries": [],
        "sources": [],
        "facts": [],
        "disclaimer": "",
        "answer": "",
        "critic_feedback": "",
        "approved": False,
        "issues": [],
        "iterations": 0,
        "max_iterations": max_iterations,
        "sources_count": 0,
        "llm_calls": 0,
        "duration_seconds": 0.0,
        "was_sensitive": is_sensitive(question),
        "critic_first_pass": False,
        "final_answer": "",
    }

    graph = build_research_graph()
    start_time = time.time()
    # recursion_limit must accommodate up to max_iterations writer<->critic loops.
    final_state = graph.invoke(
        initial_state,
        config={"recursion_limit": 50},
    )
    final_state["duration_seconds"] = time.time() - start_time
    final_state["final_answer"] = final_state.get("answer", "")
    return final_state

trace = run_research(QUESTION, max_iterations=MAX_ITERATIONS)

console.print(Panel(trace["final_answer"], title="FINAL ANSWER", style="bold green"))
print(
    f"Run summary: {trace['iterations']} iteration(s), {trace['llm_calls']} LLM calls, "
    f"{trace['sources_count']} sources, {trace['duration_seconds']:.1f}s total."
)

"""## Incentives: What Will The System Drift Toward?

A system can be structurally correct and still behave badly.

That happens when the rewards built into the system point in the wrong direction. The agents are doing exactly what they were optimized for — but what they were optimized for is not what we actually want.

This is the third pillar of the notebook.

The taxonomy tells us what roles exist. The RACI matrix tells us who is responsible. But neither of them tells us **what kind of behaviour the system will naturally drift toward over many runs**.

Some examples of incentive risks in a research system like this:

- **Thin research** — the Writer is rewarded for producing a polished answer fast, so the system may start cutting corners on retrieval.
- **Critic rubber-stamping** — the Critic is rewarded for moving things along, so it may approve too easily.
- **Missing Compliance** — sensitivity detection might miss cases, so a sensitive question slips through without a disclaimer.

The incentive scan below looks at a finished run and flags the patterns that suggest the system may be drifting in a bad direction.
"""

def scan_incentives(trace: State) -> list[IncentiveRisk]:
    risks: list[IncentiveRisk] = []

    if trace.get("iterations", 0) == 1 and len(trace.get("answer", "").split()) < 200:
        risks.append(
            IncentiveRisk(
                name="Speed over depth",
                why="Approved on first iteration with a short answer.",
                mitigation="Reward iteration; require a depth check before approval.",
            )
        )

    if trace.get("sources_count", 0) < 3:
        risks.append(
            IncentiveRisk(
                name="Thin research",
                why=f"Only {trace.get('sources_count', 0)} source(s) - risk of low-evidence answer.",
                mitigation="Set a minimum-sources threshold; require more diverse queries.",
            )
        )

    if trace.get("was_sensitive", False) and "Compliance" not in trace.get("team", []):
        risks.append(
            IncentiveRisk(
                name="Missing Compliance role",
                why="Sensitive topic detected but Compliance was not on the team.",
                mitigation="Tighten sensitivity detection; make Compliance harder to skip.",
            )
        )

    if trace.get("critic_first_pass", False) and trace.get("iterations", 0) == 1:
        risks.append(
            IncentiveRisk(
                name="Critic rubber-stamped",
                why="Approved on first try - could indicate weak gates.",
                mitigation="Add stricter Critic checks; reward thoroughness over speed.",
            )
        )

    return risks


def print_incentive_scan(risks: list[IncentiveRisk]) -> None:
    if not risks:
        console.print(Panel("No incentive risks detected - clean run!", style="bold green"))
        return

    table = Table(title="INCENTIVE SCAN", show_lines=True)
    table.add_column("Risk", style="bold red")
    table.add_column("Why")
    table.add_column("Mitigation", style="cyan")

    for risk in risks:
        table.add_row(risk.name, risk.why, risk.mitigation)

    console.print(table)

risks = scan_incentives(trace)
print_incentive_scan(risks)

"""## Final Takeaways

At this point, the full conceptual chain should be visible:

- The **question** anchors the run.
- The **taxonomy** defines what roles exist.
- **Team selection** decides which of those roles are needed now.
- The **RACI matrix** makes responsibility and accountability explicit.
- The **orchestrator** (now a `StateGraph`) turns that structure into an iterative workflow.
- The **final answer** is the output of that workflow.
- The **incentive scan** asks whether the system may have behaved badly even if the output looked acceptable.

A compact way to remember the three main ideas is:

- **Taxonomy** answers: *What roles exist?*
- **RACI** answers: *Who does what, and who owns the result?*
- **Incentives** answer: *What behavior will this system naturally drift toward?*

If you want to continue in class, the natural extension is to change `QUESTION` and rerun the notebook to see how the selected team, RACI matrix, and incentive flags change.

## Serialization: The Schemas Were Already There

Look back at how we modelled the running pipeline:

- `State` (TypedDict)
- `RACIEntry` (dataclass)
- `IncentiveRisk` (dataclass)

Each one is a plain container of fields with primitive types. No methods, no behavior. That is exactly the shape of **a schema** — data designed to cross a boundary.

So far the boundary has been invisible because every node in the graph runs in the same Python process. They share memory, so the `State` produced by one node and consumed by the next never had to be serialized — it was the same object.

But the moment any of these things become true:

- the orchestrator runs on one machine, the scanner on another,
- the trace must be written to disk for audit,
- a different team needs to read your trace format,

...the schema must be serialized. And because it was already designed as a schema, **serialization is a one-line change**, not a refactor.

### Why TypedDict (and dataclasses), not raw dicts?

A raw dict has no schema. Anyone can put any key into it. A `TypedDict` declares a contract: these are the fields, these are the types, this is the shape. The contract is what makes the data safely transportable.

### Versioning

The moment data crosses a boundary, you have to think about version mismatch. What if the orchestrator is on v2 of the schema and the scanner is still on v1? We add a `SCHEMA_VERSION` constant so consumers can detect this.

### What this section will show

We will:

1. Serialize the existing `trace` (a `State`) to JSON.
2. Print the wire format.
3. Deserialize it back.
4. Assert the round-trip is lossless.

The point is not the code (it is trivial). The point is the **realization**: you have been designing wire formats this whole time. You just did not call them that.
"""

import json

SCHEMA_VERSION = "1.0"


def serialize_trace(trace: State) -> str:
    """Convert a State into a JSON string ready for disk, network, or audit log.

    Notes for students:
    - State is already a TypedDict (= a plain dict at runtime), so json.dumps works directly.
    - We attach SCHEMA_VERSION so any consumer can check compatibility.
    - The output is a string. That is the point - it can now leave this process.
    """
    payload = {
        "schema_version": SCHEMA_VERSION,
        "trace": dict(trace),
    }
    return json.dumps(payload, indent=2, default=str)


def deserialize_trace(json_str: str) -> State:
    """Reconstruct a State from its JSON wire format.

    Notes for students:
    - We check SCHEMA_VERSION first. In a real system, a mismatch would either
      trigger a migration or be rejected. Here we just warn.
    - We then return the dict as a State (TypedDict accepts dict at runtime).
    """
    payload = json.loads(json_str)

    if payload.get("schema_version") != SCHEMA_VERSION:
        console.print(
            f"[yellow]Warning: schema version mismatch "
            f"(got {payload.get('schema_version')}, expected {SCHEMA_VERSION})[/yellow]"
        )

    return payload["trace"]  # type: ignore[return-value]

# Demo: round-trip the trace we already produced earlier in the notebook.
# This proves the schema is serializable WITHOUT changing anything about how
# the orchestrator or scanner work today.

console.print(Panel("SERIALIZING THE EXISTING TRACE", style="bold cyan"))

wire_format = serialize_trace(trace)
console.print(wire_format)

console.print(Panel("DESERIALIZING BACK", style="bold cyan"))

restored = deserialize_trace(wire_format)
console.print(f"Restored question: {restored['question']}")
console.print(f"Restored team:     {restored['team']}")
console.print(f"Restored llm_calls: {restored['llm_calls']}")

# Round-trip check.
assert restored["question"] == trace["question"]
assert restored["team"] == trace["team"]
assert restored["llm_calls"] == trace["llm_calls"]
console.print("[bold green]Round-trip OK - the schema travelled across the boundary intact.[/bold green]")

"""## Communication Protocols: When Agents Stop Sharing Memory

Today, every agent in this notebook lives in the same Python process. When the LangGraph orchestrator routes from `planner` to `searcher`, a lot of things happen *for free* because of shared memory:

| What you get for free in shared memory | What you must add when crossing a network |
|----------------------------------------|-------------------------------------------|
| Caller identity (it is whoever is running the code) | A `sender` field |
| Ordering (return values match calls) | A `task_id` per request |
| Routing (LangGraph finds the next node) | A `receiver` field |
| Intent (the function does one thing) | An `intent` field |
| Error correlation (stack traces) | A `correlation_id` to link related calls |
| Payload separation (no middleware) | Envelope vs payload separation |

The moment one agent moves to another machine, **all of these implicit things must become explicit**. That is what a communication protocol is. It is not bureaucracy — it is the minimum information needed to recover, on a network, the things that were free in shared memory.

### The Envelope

A communication protocol envelope looks like this:

```python
{
    "task_id":        "...",   # so responses can be matched to requests
    "sender":         "...",   # so the receiver can authorize the call
    "receiver":       "...",   # so gateways and routers know where to send it
    "intent":         "...",   # so the agent knows which of its skills to invoke
    "payload":        {...},   # the actual application data
    "correlation_id": "...",   # so all messages from one user request can be traced together
}
```

Each field replaces something that was free in shared memory. Remove `task_id` and you cannot match responses to requests in async systems. Remove `sender` and you cannot enforce authorization. Remove `receiver` and you cannot route through a gateway. Remove `intent` and you have assumed agents do only one thing. Remove envelope/payload separation and middleware will accidentally log your secrets.

### A2A: The Accepted Standard

**A2A (Agent-to-Agent)** is the protocol for letting agents built by different teams, on different frameworks, possibly running on different machines, talk to each other. Originally proposed by Google in 2024.

In 2025, **ACP (Agent Communication Protocol)** from IBM was merged into A2A under the Linux Foundation. So today, A2A is the unified standard. ACP is folded in.

The minimum requirements to call something "A2A":

1. **Agent Card** — a JSON document at `/.well-known/agent.json` describing the agent (name, skills, endpoint).
2. **HTTP endpoint** that accepts task messages.
3. **Standard envelope** — `task_id`, `sender`, `receiver`, `intent`, `payload`.
4. **Standard response format** — result or error, tied back to the request via `task_id`.

### What this section will show

We will not implement real HTTP or real A2A. Instead, we will simulate the **shape** of message-passing in-process so the envelope concept becomes concrete. We will:

1. Define the `Message` dataclass (the envelope).
2. Define a tiny in-memory `MessageBus`.
3. Refactor *only* the Planner → Searcher interaction to go through the bus.
4. Leave the rest of the pipeline alone, so the contrast is visible.

### Do we still need the orchestrator?

Yes. A2A does not eliminate the orchestrator — it changes the orchestrator's job from *calling functions* (or routing graph nodes) to *speaking a protocol*. The taxonomy stays. The RACI stays. What changes is that "Responsible" agents can now live anywhere. Someone still has to be Accountable for the run, and that someone is still the orchestrator.
"""

import uuid
from typing import Any, Callable


@dataclass
class Message:
    """A communication envelope. The minimum information needed when agents
    do not share memory.

    Notes for students:
    - task_id: lets us match responses to requests even when calls are async.
    - sender / receiver: identity, for authorization and routing.
    - intent: which capability of the receiver are we invoking.
    - payload: the application data - kept SEPARATE from the envelope so that
               middleware (logging, auth) can read the envelope without
               touching potentially sensitive payload contents.
    - correlation_id: links every message that came from the same user request,
                      so we can reconstruct a distributed trace later.
    """
    task_id: str
    sender: str
    receiver: str
    intent: str
    payload: dict[str, Any]
    correlation_id: str


class MessageBus:
    """A tiny in-memory message bus. In a real A2A system, this would be HTTP
    calls between separate servers. Here, we keep it in-process so the
    *shape* of message passing is visible without the distraction of networking.
    """

    def __init__(self) -> None:
        self._handlers: dict[str, Callable[[Message], Message]] = {}

    def register(self, agent_name: str, handler: Callable[[Message], Message]) -> None:
        """An agent registers itself on the bus and declares how it handles
        incoming messages. In real A2A, this is the Agent Card + HTTP endpoint.
        """
        self._handlers[agent_name] = handler

    def send(self, message: Message) -> Message:
        """Deliver a message to its receiver and return the response message.

        Notes for students:
        - In a real system this would be an HTTP POST to the receiver's endpoint.
        - The response is itself a Message, with the same correlation_id, so
          the caller can match it.
        """
        if message.receiver not in self._handlers:
            raise ValueError(f"No agent registered as '{message.receiver}'")

        console.print(f"[dim]bus: {message.sender} -> {message.receiver} "
                      f"(intent={message.intent}, task_id={message.task_id[:8]}...)[/dim]")

        handler = self._handlers[message.receiver]
        return handler(message)


# Build a small bus and register Planner + Searcher as if they were independent services.
bus = MessageBus()


def planner_handler(msg: Message) -> Message:
    """Wraps the existing planner_agent function in an envelope-speaking handler."""
    question = msg.payload["question"]
    queries = planner_agent(question)
    return Message(
        task_id=str(uuid.uuid4()),
        sender="planner",
        receiver=msg.sender,
        intent="plan_result",
        payload={"queries": queries},
        correlation_id=msg.correlation_id,
    )


def searcher_handler(msg: Message) -> Message:
    """Wraps the existing searcher_agent function in an envelope-speaking handler."""
    queries = msg.payload["queries"]
    sources = searcher_agent(queries)
    return Message(
        task_id=str(uuid.uuid4()),
        sender="searcher",
        receiver=msg.sender,
        intent="search_result",
        payload={"sources": sources},
        correlation_id=msg.correlation_id,
    )


bus.register("planner", planner_handler)
bus.register("searcher", searcher_handler)

# Demo: run the Planner -> Searcher exchange THROUGH the bus instead of as
# direct Python calls. The result is identical, but the *shape* changes:
# every interaction is now an explicit, serializable Message envelope.

from dataclasses import asdict

console.print(Panel("PLANNER -> SEARCHER VIA MESSAGE BUS", style="bold cyan"))

# Every message in this exchange shares one correlation_id, so a future
# distributed trace can stitch them together.
correlation_id = str(uuid.uuid4())

# 1. Orchestrator asks Planner for sub-queries.
plan_request = Message(
    task_id=str(uuid.uuid4()),
    sender="orchestrator",
    receiver="planner",
    intent="plan",
    payload={"question": QUESTION},
    correlation_id=correlation_id,
)
plan_response = bus.send(plan_request)

# 2. Orchestrator forwards Planner's queries to Searcher.
search_request = Message(
    task_id=str(uuid.uuid4()),
    sender="orchestrator",
    receiver="searcher",
    intent="search",
    payload={"queries": plan_response.payload["queries"]},
    correlation_id=correlation_id,
)
search_response = bus.send(search_request)

# 3. Print the envelopes - notice how they serialize cleanly because they
#    are dataclasses (callback to the Serialization section above).
console.print(Panel("PLAN REQUEST ENVELOPE", style="cyan"))
console.print(json.dumps(asdict(plan_request), indent=2))

console.print(Panel("SEARCH RESPONSE ENVELOPE (truncated payload)", style="cyan"))
search_response_view = asdict(search_response)
search_response_view["payload"] = {
    "sources_count": len(search_response.payload["sources"]),
    "first_source_url": search_response.payload["sources"][0]["url"]
    if search_response.payload["sources"] else None,
}
console.print(json.dumps(search_response_view, indent=2))

console.print(f"\n[bold green]All messages share correlation_id={correlation_id[:8]}... - "
              f"this is how you build a distributed trace.[/bold green]")

"""## Reflexion: From Amnesia to Episodic Memory

Look at how the current orchestrator handles Critic feedback. Inside `critic_node`:

```python
updates["critic_feedback"] = "; ".join(issues)
```

That single line **overwrites** feedback every iteration. So if iteration 1's Critic said *"missing citations"* and iteration 2's Critic said *"too vague"*, by iteration 3 the Writer only sees *"too vague"*. The lesson from iteration 1 is gone.

This is **amnesia**. The system has a Critic loop but no memory of what the Critic has said before.

### What Reflexion changes

Reflexion (Shinn et al., 2023) adds **episodic memory of past failures**. Instead of overwriting feedback, every Critic rejection is converted into a structured `Reflection` and *appended* to the state. The Writer then sees the *full history* of lessons on its next attempt — not just the most recent complaint.

Two important details:

1. A reflection is not the raw critic feedback. It is **a lesson learned** — something like "I must include citations even when summarizing" rather than "missing citations." This forces the system to abstract from a specific failure to a general rule.
2. The Writer prompt is updated to include all past reflections. So iteration 3's Writer is now operating with the wisdom of iterations 1 and 2.

### The failure mode worth teaching

Reflexion is not a free win. It introduces a new failure mode: **rationalization**. The agent may generate lessons that *justify* its past behavior instead of correcting it. A weak reflector might write "the Critic was being too strict" instead of "I need to add citations." The lessons accumulate, but the system does not actually improve — it just gets better at defending itself.

This connects directly back to the **incentive scan** from earlier in this notebook. Reflexion is a structural change. Whether it produces real learning or just rationalization depends on incentive design — what is the reflector rewarded for?

### Sir, the code change is small

The code change is: one new dataclass, one extension to `State` (an `episodic_memory` field), and a new variant of the critic node that **appends** to memory instead of overwriting feedback. The teaching value here is in the *concept* (memory vs amnesia, structural change vs incentive change), not the implementation. We will run the same anchor question, with Reflexion enabled, and inspect the episodic memory to see what the system actually learned across iterations.
"""

@dataclass
class Reflection:
    """One structured lesson learned from a past Critic rejection.

    Notes for students:
    - what_failed: a short description of the specific failure.
    - lesson_learned: the *generalized* rule the agent should follow next time.
                      The generalization step is what distinguishes Reflexion
                      from simple feedback-passing.
    """
    iteration: int
    what_failed: str
    lesson_learned: str


def reflector_agent(question: str, draft: str, critic_issues: list[str], iteration: int) -> Reflection:
    """Convert raw Critic issues into a structured, generalized lesson.

    In a real system this would call an LLM with a careful prompt that asks
    for a *general* rule rather than a specific complaint. Here we use a
    simple deterministic rule so the demo runs cheaply and reproducibly.

    Notes for students:
    - The temptation is to just store the raw critic_issues. Don't.
    - The whole point is the abstraction step: a specific failure -> a general lesson.
    - That step is also where rationalization can creep in. A weak reflector
      will write lessons that excuse the agent instead of improving it.
    """
    what_failed = "; ".join(critic_issues)

    # A trivial generalization rule for teaching purposes. In production this
    # would be an LLM call with an explicit prompt to produce a rule, not a complaint.
    lesson_parts: list[str] = []
    joined = what_failed.lower()
    if "citation" in joined or "source" in joined:
        lesson_parts.append("Always cite at least one source per factual claim.")
    if "vague" in joined or "specific" in joined:
        lesson_parts.append("Prefer concrete numbers and named examples over generalities.")
    if "incomplete" in joined or "missing" in joined:
        lesson_parts.append("Address every part of the question, not just the easy parts.")
    if not lesson_parts:
        lesson_parts.append("Treat critic feedback as a constraint, not a suggestion.")

    return Reflection(
        iteration=iteration,
        what_failed=what_failed,
        lesson_learned=" ".join(lesson_parts),
    )

# A Reflexion-enabled graph. The structure is identical to the original graph;
# the ONLY behavioural change is in the writer/critic nodes:
#  - writer reads accumulated lessons from state["episodic_memory"]
#  - critic appends a Reflection to state["episodic_memory"] on rejection,
#    instead of overwriting state["critic_feedback"].

def writer_node_reflexion(state: State) -> dict:
    console.print("Writer -> synthesizing answer (with episodic memory)...")

    # Reflexion change: build feedback from the FULL memory of past lessons.
    memory = state.get("episodic_memory", [])
    if memory:
        accumulated_lessons = "\n".join(
            f"- (iter {r.iteration}) {r.lesson_learned}" for r in memory
        )
        feedback = f"Lessons from previous attempts:\n{accumulated_lessons}"
    else:
        feedback = ""

    answer = writer_agent(
        state["question"],
        state.get("sources", []),
        state.get("facts", []),
        state.get("disclaimer", ""),
        feedback,
    )
    console.print(f"   Draft ready ({len(answer.split())} words)")
    iteration = state.get("iterations", 0) + 1
    console.print(Panel(f"ITERATION {iteration} (Reflexion enabled)", style="bold green"))
    return {
        "answer": answer,
        "iterations": iteration,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }


def critic_node_reflexion(state: State) -> dict:
    console.print("Critic -> reviewing...")
    approved, issues = critic_agent(
        state["question"],
        state.get("answer", ""),
        state.get("sources", []),
    )

    updates: dict = {
        "approved": approved,
        "issues": issues,
        "llm_calls": state.get("llm_calls", 0) + 1,
    }

    if approved:
        console.print("   APPROVED")
        if state.get("iterations", 0) == 1:
            updates["critic_first_pass"] = True
    else:
        # Reflexion change: APPEND a generalized lesson to episodic memory
        # instead of overwriting critic_feedback.
        reflection = reflector_agent(
            state["question"],
            state.get("answer", ""),
            issues,
            state.get("iterations", 0),
        )
        memory = list(state.get("episodic_memory", []))
        memory.append(reflection)
        updates["episodic_memory"] = memory
        console.print(f"   REJECTED - reflection added: {reflection.lesson_learned}")
        if state.get("iterations", 0) >= state.get("max_iterations", MAX_ITERATIONS):
            console.print("   Max iterations reached.")

    return updates


def build_research_graph_reflexion():
    graph = StateGraph(State)

    graph.add_node("planner", planner_node)
    graph.add_node("searcher", searcher_node)
    graph.add_node("reader", reader_node)
    graph.add_node("compliance", compliance_node)
    graph.add_node("writer", writer_node_reflexion)
    graph.add_node("critic", critic_node_reflexion)

    graph.add_edge(START, "planner")
    graph.add_edge("planner", "searcher")
    graph.add_edge("searcher", "reader")
    graph.add_edge("reader", "compliance")
    graph.add_edge("compliance", "writer")
    graph.add_edge("writer", "critic")
    graph.add_conditional_edges(
        "critic",
        critic_router,
        {"writer": "writer", "end": END},
    )

    return graph.compile()


def run_research_with_reflexion(question: str, max_iterations: int = 3) -> State:
    team = select_team(question)
    console.print(f"\nSELECTED TEAM ({len(team)} agents): {', '.join(team)}\n")

    initial_state: State = {
        "question": question,
        "team": team,
        "queries": [],
        "sources": [],
        "facts": [],
        "disclaimer": "",
        "answer": "",
        "critic_feedback": "",
        "approved": False,
        "issues": [],
        "iterations": 0,
        "max_iterations": max_iterations,
        "sources_count": 0,
        "llm_calls": 0,
        "duration_seconds": 0.0,
        "was_sensitive": is_sensitive(question),
        "critic_first_pass": False,
        "final_answer": "",
        "episodic_memory": [],
    }

    graph = build_research_graph_reflexion()
    start_time = time.time()
    final_state = graph.invoke(initial_state, config={"recursion_limit": 50})
    final_state["duration_seconds"] = time.time() - start_time
    final_state["final_answer"] = final_state.get("answer", "")
    return final_state

# Demo: re-run the same anchor question with Reflexion enabled, then
# inspect the episodic memory to see what the system actually learned
# across iterations.

console.print(Panel("RE-RUNNING WITH REFLEXION", style="bold magenta"))

reflexion_trace = run_research_with_reflexion(QUESTION, max_iterations=3)

console.print(Panel(reflexion_trace["final_answer"], title="FINAL ANSWER (Reflexion)", style="bold green"))

# Inspect episodic memory.
memory: list[Reflection] = reflexion_trace.get("episodic_memory", [])

if not memory:
    console.print("[yellow]No reflections recorded - Critic approved on first pass.[/yellow]")
else:
    table = Table(title="EPISODIC MEMORY", show_lines=True)
    table.add_column("Iter", style="bold")
    table.add_column("What Failed")
    table.add_column("Lesson Learned", style="cyan")
    for r in memory:
        table.add_row(str(r.iteration), r.what_failed, r.lesson_learned)
    console.print(table)

# Re-run the incentive scan on the new trace and see if anything changed.
console.print(Panel("INCENTIVE SCAN (Reflexion run)", style="bold yellow"))
reflexion_risks = scan_incentives(reflexion_trace)
print_incentive_scan(reflexion_risks)

"""## Human-in-the-Loop: When the Critic Is Not Enough

For most questions, the automated Critic is a good enough gate. But for **sensitive topics** — medical, legal, tax, financial — even a perfectly approved draft should not be released without a human reviewing it.

So we add a **second gate, after the Critic, before the final answer is returned**.

### How RACI shifts

In the original notebook, the Critic was always *Accountable*. That is fine for ordinary questions. For sensitive runs, accountability should rise to a human:

| Run type | Responsible | Accountable | Consulted |
|----------|-------------|-------------|-----------|
| Ordinary | Writer | **Critic** | Reader, Compliance |
| Sensitive (with HITL) | Writer | **Human** | **Critic**, Reader, Compliance |

The Critic does not disappear — it becomes *Consulted*. Its judgment still matters, but the final say is human.

This is one of the most important RACI lessons: **role assignment is not fixed; it shifts with risk**. The same agent can be Accountable on one run and Consulted on another, depending on what is at stake.

### The trigger

We trigger HITL only when `Compliance` is on the team — i.e., only when the question was already flagged as sensitive by the team selector earlier in the notebook. So the gate appears for tax, medical, legal, financial questions, but not for ordinary ones.

### The flow

1. Writer produces draft.
2. Critic reviews. If rejected → loop continues as before.
3. Critic approves → if `Compliance` is on the team, prompt the human.
4. Human approves → final answer returned.
5. Human rejects → human's reason is treated like Critic feedback, loop continues.

### Pedagogical note

In the vanilla notebook this used Python's `input()`. In LangGraph we can do this much more cleanly with the framework's built-in **`interrupt()`** primitive plus a checkpointer (`MemorySaver`). When the graph hits an `interrupt`, it pauses, the controlling code asks the human for input, and then resumes via `Command(resume=...)`. This is the same shape as the original — pause, wait for human, resume — but it is the idiomatic LangGraph way and it is exactly how a real Slack approval / webhook gate would be wired in production.

In a non-interactive environment (a notebook test runner with no stdin), we fall back to auto-approve so the demo still completes — same behaviour as the original `EOFError` fallback.
"""

from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt, Command


def human_review_node(state: State) -> dict:
    """The new HITL gate. Only fires when Compliance is on the team AND the
    Critic has approved. Pauses the graph using LangGraph's interrupt() and
    waits for human input."""
    # Only run for sensitive questions. For non-sensitive runs, this node
    # is a no-op pass-through.
    if "Compliance" not in state.get("team", []):
        return {}
    if not state.get("approved", False):
        return {}

    console.print(Panel(state.get("answer", ""), title="DRAFT FOR HUMAN REVIEW", style="yellow"))
    console.print("[bold yellow]This is a sensitive topic. Human approval required.[/bold yellow]")

    # interrupt() pauses the graph. The controlling code (the cell below)
    # is responsible for asking the human and resuming with Command(resume=...).
    decision = interrupt(
        {
            "draft": state.get("answer", ""),
            "question": state["question"],
            "prompt": "Approve this draft? Reply 'y' to approve or a reason text to reject.",
        }
    )

    # decision is whatever was passed via Command(resume=...) by the caller.
    if isinstance(decision, str) and decision.strip().lower() == "y":
        console.print("[bold green]   HUMAN APPROVED - final answer accepted.[/bold green]")
        return {"approved": True}

    # Anything else is treated as a rejection reason.
    reason = decision if isinstance(decision, str) else "Human rejected without reason"
    console.print(f"[bold red]   HUMAN REJECTED: {reason}[/bold red]")
    return {
        "approved": False,
        "critic_feedback": f"Human reviewer said: {reason}",
    }


def human_router(state: State) -> str:
    """After the human review, either we are done or we go back to the writer."""
    if state.get("approved", False):
        return "end"
    if state.get("iterations", 0) >= state.get("max_iterations", MAX_ITERATIONS):
        return "end"
    return "writer"


def build_research_graph_hitl():
    """Same graph as before, but with a human_review node sitting between the
    Critic and the END for sensitive runs."""
    graph = StateGraph(State)

    graph.add_node("planner", planner_node)
    graph.add_node("searcher", searcher_node)
    graph.add_node("reader", reader_node)
    graph.add_node("compliance", compliance_node)
    graph.add_node("writer", writer_node)
    graph.add_node("critic", critic_node)
    graph.add_node("human_review", human_review_node)

    graph.add_edge(START, "planner")
    graph.add_edge("planner", "searcher")
    graph.add_edge("searcher", "reader")
    graph.add_edge("reader", "compliance")
    graph.add_edge("compliance", "writer")
    graph.add_edge("writer", "critic")

    # If Critic rejects, loop back to the Writer. If Critic approves, go to
    # the human review gate (which is a no-op for non-sensitive runs).
    graph.add_conditional_edges(
        "critic",
        lambda s: "human_review" if s.get("approved", False) else critic_router(s),
        {"writer": "writer", "human_review": "human_review", "end": END},
    )

    # After the human review, either end or loop back to the writer.
    graph.add_conditional_edges(
        "human_review",
        human_router,
        {"writer": "writer", "end": END},
    )

    # Checkpointer is required for interrupt() to work.
    return graph.compile(checkpointer=MemorySaver())


def run_research_with_hitl(question: str, max_iterations: int = 2) -> State:
    """Run the HITL-enabled graph. If interrupt() fires, ask the human and
    resume with Command(resume=...)."""
    team = select_team(question)
    console.print(f"\nSELECTED TEAM ({len(team)} agents): {', '.join(team)}\n")

    initial_state: State = {
        "question": question,
        "team": team,
        "queries": [],
        "sources": [],
        "facts": [],
        "disclaimer": "",
        "answer": "",
        "critic_feedback": "",
        "approved": False,
        "issues": [],
        "iterations": 0,
        "max_iterations": max_iterations,
        "sources_count": 0,
        "llm_calls": 0,
        "duration_seconds": 0.0,
        "was_sensitive": is_sensitive(question),
        "critic_first_pass": False,
        "final_answer": "",
    }

    graph = build_research_graph_hitl()
    config = {"configurable": {"thread_id": str(uuid.uuid4())}, "recursion_limit": 50}
    start_time = time.time()

    # First invocation - runs until the graph either finishes or hits interrupt().
    result = graph.invoke(initial_state, config=config)

    # Loop while the graph is paused on a human-review interrupt.
    while True:
        snapshot = graph.get_state(config)
        # If there are no more pending tasks, the graph is done.
        if not snapshot.next:
            break

        # Pull the interrupt payload (the dict passed to interrupt()).
        interrupts = []
        for task in snapshot.tasks:
            interrupts.extend(task.interrupts)
        if not interrupts:
            break

        # Ask the human. Fallback to auto-approve in non-interactive contexts
        # (same shape as the vanilla EOFError fallback).
        try:
            human_decision = input("Approve this draft? (y / reason): ").strip()
        except EOFError:
            console.print("[dim](non-interactive - defaulting to approve)[/dim]")
            human_decision = "y"

        if human_decision.lower() != "y" and human_decision != "":
            # Treat as a rejection - pass the reason through.
            result = graph.invoke(Command(resume=human_decision), config=config)
        else:
            result = graph.invoke(Command(resume="y"), config=config)

    result["duration_seconds"] = time.time() - start_time
    result["final_answer"] = result.get("answer", "")
    return result

# Demo: run a deliberately sensitive question to trigger Compliance, which
# in turn triggers the human gate. Watch the RACI shift in action - Critic
# becomes Consulted, Human becomes Accountable.

SENSITIVE_QUESTION = "What are the tax implications of converting a 401k to a Roth IRA?"

console.print(Panel(f"SENSITIVE QUESTION: {SENSITIVE_QUESTION}", style="bold red"))
console.print("[dim]Note: when prompted, type 'y' to approve or a reason to reject.[/dim]\n")

hitl_trace = run_research_with_hitl(SENSITIVE_QUESTION, max_iterations=2)

console.print(Panel(hitl_trace["final_answer"], title="FINAL ANSWER (after HITL)", style="bold green"))
print(
    f"Run summary: {hitl_trace['iterations']} iteration(s), {hitl_trace['llm_calls']} LLM calls, "
    f"{hitl_trace['sources_count']} sources, {hitl_trace['duration_seconds']:.1f}s total."
)

"""## Updated Takeaways: Four Pillars + Four Extensions

The original four pillars of this notebook were:

- **Taxonomy** — what roles exist?
- **RACI** — who does what, who owns it?
- **Orchestration** — how does the work flow?
- **Incentives** — what will the system drift toward?

We then layered four extensions on top:

- **Serialization** — the schemas were already there. The hard part (designing `State` as a `TypedDict`) was done on day one. Crossing a boundary became a one-line change because of that. Lesson: **schema-first design makes future extensions cheap.**
- **Communication Protocols (A2A)** — every field in the message envelope replaces something that was free in shared memory. The protocol is not bureaucracy; it is the minimum information needed to recover identity, ordering, routing, intent, and tracing on a network.
- **Reflexion** — replacing `=` with `.append()` turned an amnesiac Critic loop into a system with episodic memory. The code was small. The behavioural change is large. The new failure mode (rationalization instead of learning) is large too.
- **Human-in-the-Loop** — the same agent (Critic) is Accountable on one run and Consulted on the next, depending on the risk of the question. RACI is not static; it shifts with stakes. In LangGraph, this is expressed cleanly with `interrupt()` + checkpointer instead of a raw `input()` call.

### What the LangGraph migration actually changed

- `RunTrace` (dataclass) → `State` (TypedDict that flows through the graph).
- Hand-rolled `for` loop orchestrator → `StateGraph` with conditional edges.
- Manual `if "Foo" in team` checks scattered through the loop → no-op early returns inside each node.
- `input()` for HITL → `interrupt()` + `Command(resume=...)` with a `MemorySaver` checkpointer.

Everything else — agents, prompts, Critic thresholds, Reflexion logic, A2A envelope, incentive scan — stayed identical. The point of the migration is to show students that **the same conceptual system can be expressed in the framework they will actually use in production**, without any of the concepts changing meaning.

### One open question to leave with

> *What new incentive risk does Reflexion introduce?*

The reflector is rewarded for producing lessons. But there is no automatic check that the lessons are *correct* — only that they exist. A weak reflector can produce lessons that excuse the agent's past behaviour rather than correct it. The episodic memory grows; the actual behaviour does not improve.

This is a perfect callback to the incentive scan: **structural changes (Reflexion) only help if incentive design (what the reflector is rewarded for) is also right**. Structure without aligned incentives drifts. Incentives without supporting structure cannot be enforced. You need both.

### A compact way to remember the whole notebook

| Pillar | Question it answers |
|--------|---------------------|
| Taxonomy | What roles exist? |
| RACI | Who owns what? |
| Orchestration | How does the work flow? |
| Incentives | What will the system drift toward? |
| Serialization | What crosses the boundary? |
| Protocols | How do they speak across it? |
| Reflexion | What does the system remember? |
| Human-in-the-loop | When does a human decide? |

Eight questions. One small notebook. Same anchor question runs the whole way through.

~~~

TAXONOMY, RACI & INCENTIVES — Now in LangGraph
│
│   Anchor question: "Deep Research on Jobs in demand"
│   Vanilla → LangGraph migration: same concepts, framework primitives.
│
├── 1. TAXONOMY ──────────────────── "What roles exist?"
│   │
│   ├── Concept: Catalog of agents, each with ONE focused mission.
│   │
│   ├── 6 Roles: Planner, Searcher, Reader, Writer, Critic, Compliance
│   │
│   ├── Vanilla:    a Python dict (TAXONOMY = {...})
│   ├── LangGraph:  same Python dict — taxonomy is framework-AGNOSTIC.
│   │               Each role becomes a NODE in the graph (later in section 4).
│   │
│   └── Lesson: Taxonomy is design, not framework. The same dict works anywhere.
│
├── 2. TEAM SELECTION (Router) ───── "Which roles do we need NOW?"
│   │
│   ├── Vanilla:    if/else checks before the for-loop
│   ├── LangGraph:  TWO valid patterns:
│   │     │
│   │     ├── (a) Pre-graph routing (what we used):
│   │     │     team computed BEFORE graph.invoke()
│   │     │     stored in state["team"]
│   │     │     each node: if "MyRole" not in state["team"]: return {}
│   │     │     ↑ dead-simple, no extra graph nodes
│   │     │
│   │     └── (b) Router node + conditional edges (more advanced):
│   │           a "router" node returns "planner" or "searcher" etc.
│   │           graph.add_conditional_edges("router", route_fn, {...})
│   │           ↑ cleaner for complex routing, overkill for teaching
│   │
│   └── Lesson: Routing logic stays in Python — LangGraph just executes it.
│
├── 3. RACI ───────────────────────── "Who owns what?"
│   │
│   ├── Vanilla:    list[RACIEntry] dataclass
│   ├── LangGraph:  same dataclass — RACI is documentation, not runtime.
│   │
│   └── Lesson: RACI is metadata about the system, not part of execution.
│               Lives outside the graph.
│
├── 4. ORCHESTRATION ──────────────── "How does work FLOW?"  ★ BIG MIGRATION ★
│   │
│   ├── Vanilla:                          LangGraph:
│   │   ┌─────────────────┐              ┌─────────────────────────────────┐
│   │   │ for iteration   │              │ graph = StateGraph(State)        │
│   │   │   in range(...):│              │ graph.add_node(...)              │
│   │   │   if "X" in team│              │ graph.add_edge(...)              │
│   │   │     foo_agent() │              │ graph.add_conditional_edges(...) │
│   │   │   if approved:  │              │ graph.compile()                  │
│   │   │     break       │              │ graph.invoke(state)              │
│   │   └─────────────────┘              └─────────────────────────────────┘
│   │
│   ├── 4 LangGraph primitives you MUST know:
│   │     │
│   │     ├── State (TypedDict) ─── the data that flows through every node
│   │     │   class State(TypedDict, total=False):
│   │     │       question: str
│   │     │       team: list[str]
│   │     │       sources: list
│   │     │       iterations: int
│   │     │       ...
│   │     │
│   │     ├── Node ─── a function: State → dict (partial state update)
│   │     │   def planner_node(state: State) -> dict:
│   │     │       queries = planner_agent(state["question"])
│   │     │       return {"queries": queries, "llm_calls": ...}
│   │     │   ↑ LangGraph MERGES the returned dict into State automatically.
│   │     │
│   │     ├── Edge ─── deterministic transition between nodes
│   │     │   graph.add_edge("planner", "searcher")
│   │     │
│   │     └── Conditional Edge ─── routing function decides next node
│   │         graph.add_conditional_edges(
│   │             "critic",
│   │             critic_router,           # function: State → "writer" or "end"
│   │             {"writer": "writer", "end": END}
│   │         )
│   │
│   ├── The Critic loop in LangGraph:
│   │
│   │     START → planner → searcher → reader → compliance → writer → critic
│   │                                                                    │
│   │                              ┌──── conditional edge ───────────────┤
│   │                              │  state["approved"]?
│   │                              ▼
│   │                          [True]  → END
│   │                          [False] → "writer"  (back-edge = the loop)
│   │
│   ├── Why this is better than the for-loop:
│   │   - Workflow is DECLARATIVE — you can SEE the graph
│   │   - Each node is independently testable
│   │   - State updates are explicit and traceable
│   │   - Free observability (LangSmith plugs in directly)
│   │
│   └── Lesson: NODES = work.  EDGES = control flow.  STATE = memory.
│
├── 5. INCENTIVES ─────────────────── "What will the system DRIFT toward?"
│   │
│   ├── Vanilla:    scan_incentives(trace: RunTrace)
│   ├── LangGraph:  scan_incentives(state: State)
│   │               (RunTrace was a dataclass, State is a TypedDict — same fields)
│   │
│   ├── 4 Risks: Speed-over-depth, Thin research, Missing Compliance, Rubber-stamped
│   │
│   └── Lesson: Incentive scanning runs AFTER the graph finishes.
│               Final State has everything you need (iterations, sources_count, etc.)
│
├── 6. SERIALIZATION ──────────────── "What CROSSES the boundary?"
│   │
│   ├── Vanilla:    you must call json.dumps(asdict(trace)) MANUALLY
│   ├── LangGraph:  TWO different serialization layers — don't confuse them:
│   │     │
│   │     ├── (a) AUTOMATIC (LangGraph's checkpointer):
│   │     │     graph.compile(checkpointer=MemorySaver())
│   │     │     → State auto-serialized at every node boundary
│   │     │     → Enables interrupt(), time-travel, resume-after-crash
│   │     │     → Format is INTERNAL to LangGraph
│   │     │
│   │     └── (b) MANUAL (json.dumps for OUR wire format):
│   │           json.dumps({"schema_version": "1.0", "trace": dict(state)})
│   │           → For when State leaves LangGraph entirely
│   │             (audit DB, Slack message, gRPC call, Kafka topic)
│   │           → YOU control the format
│   │
│   ├── Why State (TypedDict) made this trivial:
│   │     - dict(state) is already a plain dict at runtime
│   │     - json.dumps works directly — no .asdict(), no Pydantic .model_dump()
│   │
│   └── Lesson: LangGraph serializes for ITS OWN purposes (checkpoints).
│               You serialize when crossing boundaries it doesn't own.
│               Schema-first design (TypedDict) makes BOTH free.
│
├── 7. A2A — COMMUNICATION PROTOCOL ─ "How do they SPEAK across the boundary?"
│   │
│   ├── Concept: Same as vanilla — envelopes replace shared-memory assumptions.
│   │            (task_id, sender, receiver, intent, payload, correlation_id)
│   │
│   ├── Vanilla:    custom MessageBus class with register() / send()
│   ├── LangGraph:  THREE valid patterns depending on what you actually need:
│   │     │
│   │     ├── (a) Single-graph LangGraph (what we did):
│   │     │     A2A is NOT needed — agents share state in-process.
│   │     │     We kept the Message dataclass purely as TEACHING material
│   │     │     to show the SHAPE of the envelope.
│   │     │
│   │     ├── (b) Multi-graph LangGraph (subgraphs):
│   │     │     Each agent is its own graph; parent graph invokes sub-graphs.
│   │     │     Still in-process — A2A still not needed.
│   │     │
│   │     └── (c) TRULY distributed (different services, different machines):
│   │           NOW you need A2A. LangGraph nodes wrap HTTP calls to remote
│   │           agents. The Message envelope IS the HTTP body.
│   │           Each remote agent exposes /.well-known/agent.json (Agent Card).
│   │
│   ├── Code logic stays the same:
│   │     @dataclass class Message: task_id, sender, receiver, intent, payload, correlation_id
│   │     The dataclass is framework-agnostic.
│   │
│   └── Lesson: LangGraph handles the IN-PROCESS case. A2A handles the
│               CROSS-NETWORK case. You may need both in production.
│
├── 8. REFLEXION ──────────────────── "What does the system REMEMBER?"
│   │
│   ├── Vanilla:    critic_feedback = "; ".join(issues)   ← OVERWRITES (amnesia)
│   ├── LangGraph:  memory.append(reflection)              ← APPENDS to State field
│   │
│   ├── ★ CRITICAL LangGraph gotcha ★
│   │     If you want a state field to persist across nodes, you MUST declare it
│   │     in the State TypedDict. Otherwise LangGraph SILENTLY DROPS it.
│   │
│   │     class State(TypedDict, total=False):
│   │         ...
│   │         episodic_memory: list   ← MUST be declared, or .append() goes nowhere
│   │
│   ├── Code change in critic_node (LangGraph version):
│   │     def critic_node_reflexion(state):
│   │         ...
│   │         if not approved:
│   │             reflection = reflector_agent(...)
│   │             memory = list(state.get("episodic_memory", []))
│   │             memory.append(reflection)
│   │             return {"episodic_memory": memory}    ← merged into State
│   │
│   ├── Bonus LangGraph feature (advanced, not used here):
│   │     Use Annotated[list, operator.add] for AUTO-APPEND merge behaviour.
│   │     Then nodes return {"episodic_memory": [reflection]} and LangGraph
│   │     concatenates instead of overwriting. Powerful for multi-agent forks.
│   │
│   └── Lesson: In LangGraph, STATE SCHEMA is the contract.
│               If a field isn't in the TypedDict, it doesn't exist.
│
└── 9. HUMAN-IN-THE-LOOP ──────────── "When does a HUMAN decide?"  ★ BIG WIN ★
    │
    ├── Vanilla approach (BAD for production):
    │     human_decision = input("Approve? y/n")
    │     ↑ blocking — Python process FROZEN until human responds.
    │     ↑ if Slack approval takes 4 hours, your server is dead for 4 hours.
    │
    ├── LangGraph approach (PRODUCTION-GRADE):
    │     │
    │     ├── (1) Define a node that calls interrupt():
    │     │       def human_review_node(state):
    │     │           if "Compliance" not in state["team"]:
    │     │               return {}                    ← skip for non-sensitive
    │     │           decision = interrupt({           ← graph PAUSES here
    │     │               "draft": state["answer"],
    │     │               "prompt": "Approve? y/reason"
    │     │           })
    │     │           return {"approved": decision == "y", ...}
    │     │
    │     ├── (2) Compile with a checkpointer:
    │     │       graph.compile(checkpointer=MemorySaver())
    │     │       ↑ checkpointer is REQUIRED for interrupt() to work.
    │     │         It saves state to disk so the graph can be resumed later.
    │     │
    │     └── (3) Resume with Command(resume=...):
    │           graph.invoke(Command(resume="y"), config={"thread_id": ...})
    │           ↑ continues from exactly where interrupt() paused.
    │           ↑ thread_id ties the resume to the original run.
    │
    ├── What this enables:
    │   - Server can serve OTHER requests while waiting for human
    │   - Approval can come from Slack/webhook/email — hours later
    │   - Checkpointer survives process restarts (use SqliteSaver in prod)
    │   - Multiple humans can review the same paused graph
    │
    ├── ★ THE RACI SHIFT (still the most important lesson) ★
    │     Ordinary run:   Writer R → Critic A
    │     Sensitive run:  Writer R → Human A → Critic C
    │
    │     Same Critic. Different role. Decided by sensitivity.
    │
    └── Lesson: input() = teaching toy.
                interrupt() + checkpointer = how Slack approvals actually work.


╔══════════════════════════════════════════════════════════════════════════╗
║   LangGraph PRIMITIVES — what you actually need to know                  ║
╠══════════════════════════════════════════════════════════════════════════╣
║                                                                          ║
║   StateGraph(State)        ← container for nodes + edges                 ║
║   add_node(name, fn)       ← register an agent function                  ║
║   add_edge(a, b)           ← unconditional transition                    ║
║   add_conditional_edges()  ← routing fn returns next node name           ║
║   compile(checkpointer=)   ← turn graph into runnable                    ║
║   invoke(state, config)    ← run end-to-end                              ║
║                                                                          ║
║   State = TypedDict        ← the data contract                           ║
║   Node returns dict        ← LangGraph merges into State                 ║
║   START / END constants    ← graph entry/exit                            ║
║                                                                          ║
║   interrupt(payload)       ← pause for human                             ║
║   Command(resume=value)    ← resume after pause                          ║
║   MemorySaver()            ← in-memory checkpointer (use Sqlite in prod) ║
║                                                                          ║
╚══════════════════════════════════════════════════════════════════════════╝

╔══════════════════════════════════════════════════════════════════════════╗
║   VANILLA → LANGGRAPH — quick translation table                          ║
╠══════════════════════════════════════════════════════════════════════════╣
║                                                                          ║
║   RunTrace (dataclass)    →   State (TypedDict)                          ║
║   for-loop orchestrator   →   StateGraph + nodes + edges                 ║
║   if/else inside loop     →   add_conditional_edges()                    ║
║   trace.field = value     →   return {"field": value} from node          ║
║   manual feedback thread  →   conditional edge back to writer            ║
║   input() blocking call   →   interrupt() + Command(resume=...)          ║
║   manual json.dumps       →   automatic via checkpointer (+ manual when  ║
║                               leaving LangGraph for external systems)    ║
║                                                                          ║
╚══════════════════════════════════════════════════════════════════════════╝

╔══════════════════════════════════════════════════════════════════════════╗
║   ONE-LINE MEMORY CARD                                                   ║
╠══════════════════════════════════════════════════════════════════════════╣
║   Taxonomy        →  what roles EXIST?                                   ║
║   Team selection  →  which roles are ACTIVE now?                         ║
║   RACI            →  who OWNS what?                                      ║
║   Orchestration   →  how does work FLOW?         (StateGraph)            ║
║   Incentives      →  what will it DRIFT toward?                          ║
║   Serialization   →  what CROSSES the boundary?  (TypedDict + checkpointer)║
║   A2A             →  how do they SPEAK across it?                        ║
║   Reflexion       →  what does it REMEMBER?      (State field + append)  ║
║   HITL            →  when does a HUMAN decide?   (interrupt + Command)   ║
╚══════════════════════════════════════════════════════════════════════════╝
"""